package ggt;


/**
* ggt/_unitImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Thursday, 12 June 2008 12:48:13 o'clock CEST
*/

public abstract class _unitImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements ggt.unit, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _unitImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setneighbors", new java.lang.Integer (0));
    _methods.put ("setpm", new java.lang.Integer (1));
    _methods.put ("sendy", new java.lang.Integer (2));
    _methods.put ("query", new java.lang.Integer (3));
    _methods.put ("response", new java.lang.Integer (4));
    _methods.put ("close", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* initial */
       case 0:  // ggt/unit/setneighbors
       {
         int pidleft = in.read_long ();
         int pidright = in.read_long ();
         int $result = (int)0;
         $result = this.setneighbors (pidleft, pidright);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ggt/unit/setpm
       {
         int pm = in.read_long ();
         this.setpm (pm);
         out = $rh.createReply();
         break;
       }


  /* rechnen */
       case 2:  // ggt/unit/sendy
       {
         int y = in.read_long ();
         this.sendy (y);
         out = $rh.createReply();
         break;
       }

       case 3:  // ggt/unit/query
       {
         this.query ();
         out = $rh.createReply();
         break;
       }

       case 4:  // ggt/unit/response
       {
         int y = in.read_long ();
         this.response (y);
         out = $rh.createReply();
         break;
       }


  /* beenden */
       case 5:  // ggt/unit/close
       {
         this.close ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ggt/unit:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _unitImplBase
