package ggt;


/**
* ggt/unit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Thursday, 12 June 2008 12:48:13 o'clock CEST
*/

public interface unit extends unitOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface unit
