package ggt;


/**
* ggt/unitOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Thursday, 12 June 2008 12:48:13 o'clock CEST
*/

public interface unitOperations 
{

  /* initial */
  int setneighbors (int pidleft, int pidright);
  void setpm (int pm);

  /* rechnen */
  void sendy (int y);
  void query ();
  void response (int y);

  /* beenden */
  void close ();
} // interface unitOperations
