package ggt;

/**
* ggt/unitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Thursday, 12 June 2008 12:48:13 o'clock CEST
*/

public final class unitHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.unit value = null;

  public unitHolder ()
  {
  }

  public unitHolder (ggt.unit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.unitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.unitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.unitHelper.type ();
  }

}
