package ggt;


/**
* ggt/unit_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Thursday, 12 June 2008 12:48:13 o'clock CEST
*/

public class unit_Tie extends _unitImplBase
{

  // Constructors
  public unit_Tie ()
  {
  }

  public unit_Tie (ggt.unitOperations impl)
  {
    super ();
    _impl = impl;
  }


  /* initial */
  public int setneighbors (int pidleft, int pidright)
  {
    return _impl.setneighbors(pidleft, pidright);
  } // setneighbors

  public void setpm (int pm)
  {
    _impl.setpm(pm);
  } // setpm


  /* rechnen */
  public void sendy (int y)
  {
    _impl.sendy(y);
  } // sendy

  public void query ()
  {
    _impl.query();
  } // query

  public void response (int y)
  {
    _impl.response(y);
  } // response


  /* beenden */
  public void close ()
  {
    _impl.close();
  } // close

  private ggt.unitOperations _impl;

} // class unit_Tie
