package chef;


/**
* chef/_koordinatorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chef.idl
* Thursday, 12 June 2008 12:48:19 o'clock CEST
*/

public class _koordinatorStub extends org.omg.CORBA.portable.ObjectImpl implements chef.koordinator
{


  /* initial */
  public int getsteeringval (org.omg.CORBA.IntHolder pnum, org.omg.CORBA.IntHolder wtime, org.omg.CORBA.IntHolder term)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getsteeringval", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                pnum.value = $in.read_long ();
                wtime.value = $in.read_long ();
                term.value = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getsteeringval (pnum, wtime, term        );
            } finally {
                _releaseReply ($in);
            }
  } // getsteeringval

  public int hello (int pid)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("hello", true);
                $out.write_long (pid);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return hello (pid        );
            } finally {
                _releaseReply ($in);
            }
  } // hello


  /* bereit */
  public void brief (int pid, int pm, int ptime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("brief", false);
                $out.write_long (pid);
                $out.write_long (pm);
                $out.write_long (ptime);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                brief (pid, pm, ptime        );
            } finally {
                _releaseReply ($in);
            }
  } // brief

  public void terminated (int pid, int ggt, int ptime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("terminated", false);
                $out.write_long (pid);
                $out.write_long (ggt);
                $out.write_long (ptime);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                terminated (pid, ggt, ptime        );
            } finally {
                _releaseReply ($in);
            }
  } // terminated


  /* beenden */
  public void closed (int pid, int pm, int ptime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("closed", false);
                $out.write_long (pid);
                $out.write_long (pm);
                $out.write_long (ptime);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                closed (pid, pm, ptime        );
            } finally {
                _releaseReply ($in);
            }
  } // closed

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chef/koordinator:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _koordinatorStub
