package chef;


/**
* chef/_koordinatorImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chef.idl
* Thursday, 12 June 2008 12:48:19 o'clock CEST
*/

public abstract class _koordinatorImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements chef.koordinator, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _koordinatorImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getsteeringval", new java.lang.Integer (0));
    _methods.put ("hello", new java.lang.Integer (1));
    _methods.put ("brief", new java.lang.Integer (2));
    _methods.put ("terminated", new java.lang.Integer (3));
    _methods.put ("closed", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* initial */
       case 0:  // chef/koordinator/getsteeringval
       {
         org.omg.CORBA.IntHolder pnum = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder wtime = new org.omg.CORBA.IntHolder ();
         org.omg.CORBA.IntHolder term = new org.omg.CORBA.IntHolder ();
         int $result = (int)0;
         $result = this.getsteeringval (pnum, wtime, term);
         out = $rh.createReply();
         out.write_long ($result);
         out.write_long (pnum.value);
         out.write_long (wtime.value);
         out.write_long (term.value);
         break;
       }

       case 1:  // chef/koordinator/hello
       {
         int pid = in.read_long ();
         int $result = (int)0;
         $result = this.hello (pid);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  /* bereit */
       case 2:  // chef/koordinator/brief
       {
         int pid = in.read_long ();
         int pm = in.read_long ();
         int ptime = in.read_long ();
         this.brief (pid, pm, ptime);
         out = $rh.createReply();
         break;
       }

       case 3:  // chef/koordinator/terminated
       {
         int pid = in.read_long ();
         int ggt = in.read_long ();
         int ptime = in.read_long ();
         this.terminated (pid, ggt, ptime);
         out = $rh.createReply();
         break;
       }


  /* beenden */
       case 4:  // chef/koordinator/closed
       {
         int pid = in.read_long ();
         int pm = in.read_long ();
         int ptime = in.read_long ();
         this.closed (pid, pm, ptime);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chef/koordinator:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _koordinatorImplBase
