package chef;


/**
* chef/koordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chef.idl
* Thursday, 12 June 2008 12:48:19 o'clock CEST
*/

public interface koordinatorOperations 
{

  /* initial */
  int getsteeringval (org.omg.CORBA.IntHolder pnum, org.omg.CORBA.IntHolder wtime, org.omg.CORBA.IntHolder term);
  int hello (int pid);

  /* bereit */
  void brief (int pid, int pm, int ptime);
  void terminated (int pid, int ggt, int ptime);

  /* beenden */
  void closed (int pid, int pm, int ptime);
} // interface koordinatorOperations
