package chef;

/**
* chef/koordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chef.idl
* Thursday, 12 June 2008 12:48:19 o'clock CEST
*/

public final class koordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public chef.koordinator value = null;

  public koordinatorHolder ()
  {
  }

  public koordinatorHolder (chef.koordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chef.koordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chef.koordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chef.koordinatorHelper.type ();
  }

}
