%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_chef
%% Source: c:/DOKUME~1/CHRIST~1/EIGENE~1/Download/cpp/cpp/chef.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_CHEF_HRL).
-define(OE_CHEF_HRL, true).




-endif.


