%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_ggt
%% Source: c:/DOKUME~1/CHRIST~1/EIGENE~1/Download/cpp/cpp/ggt.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_GGT_HRL).
-define(OE_GGT_HRL, true).




-endif.


