%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: oe_ggt
%% Source: c:/DOKUME~1/CHRIST~1/EIGENE~1/Download/cpp/cpp/ggt.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(oe_ggt).
-ic_compiled("4_2_31").


-include_lib("orber/include/ifr_types.hrl").

%% Interface functions

-export([oe_register/0, oe_unregister/0, oe_get_module/5]).
-export([oe_dependency/0]).



oe_register() ->
    OE_IFR = orber_ifr:find_repository(),

    register_tests(OE_IFR),

    _OE_1 = oe_get_top_module(OE_IFR, "IDL:ggt:1.0", "ggt", "1.0"),

    _OE_2 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:ggt/unit:1.0", "unit", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/setneighbors:1.0", "setneighbors", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), 'OP_NORMAL', [#parameterdescription{name="pidright", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
, #parameterdescription{name="pidleft", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/setpm:1.0", "setpm", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_ONEWAY', [#parameterdescription{name="pm", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/sendy:1.0", "sendy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_ONEWAY', [#parameterdescription{name="y", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/query:1.0", "query", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_ONEWAY', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/response:1.0", "response", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_ONEWAY', [#parameterdescription{name="y", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:ggt/unit/close:1.0", "close", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_ONEWAY', [], [], []),

    ok.


%% General IFR registration checks.
register_tests(OE_IFR)->
  re_register_test(OE_IFR),
  include_reg_test(OE_IFR).


%% IFR type Re-registration checks.
re_register_test(OE_IFR)->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:ggt/unit:1.0") of
    []  ->
      true;
    _ ->
      exit({allready_registered,"IDL:ggt/unit:1.0"})
 end.


%% No included idl-files detected.
include_reg_test(_OE_IFR) -> true.


%% Fetch top module reference, register if unregistered.
oe_get_top_module(OE_IFR, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'Repository_create_module'(OE_IFR, ID, Name, Version);
    Mod  ->
      Mod
   end.

%% Fetch module reference, register if unregistered.
oe_get_module(OE_IFR, OE_Parent, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'ModuleDef_create_module'(OE_Parent, ID, Name, Version);
    Mod  ->
      Mod
   end.



oe_unregister() ->
    OE_IFR = orber_ifr:find_repository(),

    oe_destroy(OE_IFR, "IDL:ggt/unit:1.0"),
    oe_destroy_if_empty(OE_IFR, "IDL:ggt:1.0"),
    ok.


oe_destroy_if_empty(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    case orber_ifr:contents(Ref, 'dk_All', 'true') of
		[] ->
		    orber_ifr:destroy(Ref),
		    ok;
		_ ->
		    ok
	    end
    end.

oe_destroy(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    orber_ifr:destroy(Ref),
	    ok
    end.



%% Idl file dependency list function
oe_dependency() ->

    [].

